### ISSUE TITLE
Persistens settings storage

### ISSUE THREAD

**Issue by Shutnik** [350d/stylish#10]
There is [modern API](https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/ExtensionSettings/ExtensionSettings.html#//apple_ref/doc/uid/TP40009977-CH11-SW14) for persistent  storage (settings are saved on clearing browser history), can you please implement it?

**Comment by 350d** [comment]
Feel free to check updated v. 1.8.7 with updated storage location. Thank you for pointing me to this option!

**Comment by Shutnik** [comment]
:thumbsup:
