### ISSUE TITLE
Extension from Apple at 1.6

### ISSUE THREAD

**Issue by sundarv85** [350d/stylish#11]
Hello

I installed extension from Apply Gallery

https://safari-extensions.apple.com/details/?id=com.sobolev.stylish-5555L95H45

It is version 1.6 and not 1.8.8. And I do not see any way to set styles. Am I missing something?

**Comment by 350d** [comment]
Latest version submitted to Gallery weeks ago, so, waiting for approval. In 1.6 you can manage your styles by clicking on S icon in toolbar.

**Comment by sundarv85** [comment]
Great. That works. Thanks.
