### ISSUE TITLE
Problems on case sensitive file systems

### ISSUE THREAD

**Issue by mumia** [350d/stylish#12]
Found out that this extension fails to load on case sensitive file system.

It fails to load the Info.plist file.

Found that adding a symbolic link info.plist => Info.plist "solves it for me. But this "fix" forces me to open the extension and then load it through the Extension Builder in Safari.

Is there any fix that could be done to solve this permanently?

**Comment by mumia** [comment]
Can the Info.plist be lowercased without issues?

**Comment by 350d** [comment]
fixed in latest version. thank you for report!

**Comment by mumia** [comment]
That should do it, but I can't seem to be able to install the extension now.
Click on the extension, Safari asks me to trust the developer, I say Trust and nothing happens.

Not sure if it's a problem problem with my Safari or with the changes you made.

Will investigate more.

Thanks for the quick response.

**Comment by 350d** [comment]
Check the version number, should be 1.9.0

**Comment by mumia** [comment]
Checked and it is 1.9.0.

If I unpack the extension and install it through the extension builder, it works.

This is very weird. Must be something with my OS X/Safari install.

**Comment by mumia** [comment]
FYI, I was able to install the extension via the Safari Extension manager.
All is good, thanks for the help.
