### ISSUE TITLE
Always "Update available!" when checking updates.

### ISSUE THREAD

**Issue by zanderzhng** [350d/stylish#13]
Mac Safari, Stylish 1.9.0.

**Comment by ylluminate** [comment]
Having the same problem here. Appears we're not getting the actual updates either even when attempting to update.

**Comment by PwnArt1st** [comment]
+1

**Comment by mustii82** [comment]
I have the same Issue its making the whole Plugin useless !!!

**Comment by 350d** [comment]
Updated version (1.9.1) submitted to the official Safari Extensions gallery. Direct download available via website.

**Comment by ylluminate** [comment]
Any reason we'd get this error when attempting to install 1.9.1 manually?
```
Safari can’t install this extension
An error occurred while installing the extension “Stylish”.
```

**Comment by mustii82** [comment]
some styles aren't recognized well after the update my plugin says there is no plugin for this page but the style manager shows the style

**Comment by PwnArt1st** [comment]
@ylluminate You need to uninstall the existing 1.9.0 from Safari before it will let you install 1.9.1

**Comment by zanderzhng** [comment]
Just remember to export your stylish list before uninstalling.

And there's a system bug, sometimes you can't install extensions directly by
clicking the "Trust" button. You need to switch "Full Keyboard Access" to "All
Controls", then use Tab to select the "Trust" button and hit spce bar.

**Comment by 350d** [comment]
@mustii82 can you reproduce this issue with any public style?

**Comment by 350d** [comment]
Guys, the bad thing about update mechanism - i can't respect your non default settings/options if style have it. For example if you trying to install a new style from userstyles.org page and you have changed some options like colors or something - there is no way to store and keep your options right now. Not sure, how many people using options for styles right now and curious about do i need to spend some time and try to implement this feature or not.

**Comment by mustii82** [comment]
@350d  youtube dark get theme :/

**Comment by zanderzhng** [comment]
It would be useful to remain the options before you add auto update feature.
