### ISSUE TITLE
Comment broke styles

### ISSUE THREAD

**Issue by denis-g** [350d/stylish#14]
Hi, i use `/* remove asian lang's */` comment in my style and this broke all user styles after this line.
After delete comment - styles work fine.
[Sample code](https://github.com/denis-g/userstyle-simply-steam-ui/blob/master/styles.css#L135)

Tested on Stylish 1.9.0, 1.9.1. MacOS 10.11.5

**Comment by 350d** [comment]
Works just fine, can you show screenshots or something?

**Comment by 350d** [comment]
In latest 1.9.3 version you can disable default css magnification function in Settings panel to get more compatibility with styles
