### ISSUE TITLE
Apply to everything but...

### ISSUE THREAD

**Issue by ylluminate** [350d/stylish#15]
It appears that a style can be applied to specific sites, but there doesn't appear to be an exclusive functionality.  For example, I have a dark theme that I want to apply to all sites BUT certain sites that have better dark themes.

Can this be done presently?

So far I only see this:
![no exclusive application](http://cl.ly/0r003e3B3n31/Image%202016-06-03%20at%201.18.52%20AM.png)

**Comment by 350d** [comment]
Regex?

**Comment by 350d** [comment]
#18
