### ISSUE TITLE
Broken in Safari 10 beta

### ISSUE THREAD

**Issue by ylluminate** [350d/stylish#17]
Found that Stylish is not showing styles that are installed in Safari 10:
![example](http://cl.ly/0h2Y0H2n0d2H/Image%202016-06-26%20at%204.50.00%20PM.png)

Yet when you go to Manage all of the styles I have installed are still there and they seem to function on visiting websites...

**Comment by 350d** [comment]
Can't reproduce on fresh Sierra Beta with Safari 10

**Comment by 350d** [comment]
1.9.3 is ready to download, this issue should be fixed
