### ISSUE TITLE
Add option for excluding websites

### ISSUE THREAD

**Issue by badrabbit** [350d/stylish#18]
Please add an option to exclude custom domains.

For example i have a style sheet that simply zooms all content to 130%. But that won't work correctly with sites like YouTube or Plex. So i need to disable the style sheet every time i visit these sites.

Thanks!

**Comment by 350d** [comment]
You can use regex in your case

**Comment by badrabbit** [comment]
But that's the problem. If i add a regexp rule and put in "https://www.youtube.com/" i can only apply the style on no other site than YouTube. Am i doing something wrong here?

**Comment by 350d** [comment]
You need something like that "https?://(?!(www.youtube.com|example.com)).*"

**Comment by badrabbit** [comment]
Thanks so much! Working now!
