### ISSUE TITLE
Not registering Styles for a site with a domain-rule

### ISSUE THREAD

**Issue by 3rdStepStudios** [350d/stylish#22]
When setting a Domain-trigger rule, and navigating to the domain set to trigger the rule, it doesn't register that the domain as having any CSS styles.
<img width="248" alt="screen shot 2016-12-31" src="https://cloud.githubusercontent.com/assets/8221867/21576720/bc29a74a-cf07-11e6-9cab-d1c37eb69bb5.png">

**Comment by 350d** [comment]
1. Check latest 1.9.3 version
2. Show your style edit screen please
