### ISSUE TITLE
Cannot perform Export due to 404 error (v1.9.2)

### ISSUE THREAD

**Issue by ylluminarious** [350d/stylish#23]
I'm running Stylish v1.9.2 and I'm getting the following error when I try to export my styles as a JSON file under the "Settings" tab:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (export.php, line 0)
```

Indeed, when I visit http://sobolev.us/download/stylish/export.php, there is a 404 error returned. [It also appears that this PHP script is hardcoded into this button](https://github.com/350d/stylish/blob/master/stylish.safariextension/settings.html#L47), and is presumably required for this "Export" action to work. How can I resolve this issue so that I can get the "Export" functionality working again?

**Comment by 350d** [comment]
Try now

**Comment by ylluminarious** [comment]
@350d It works. Thanks!
