### ISSUE TITLE
Maximum style length?

### ISSUE THREAD

**Issue by silverwind** [350d/stylish#25]
Is it possible that there is a limit on how big a user stylesheet can be in bytes/lines? I'm observing that certain rules from http://userstyles.org/styles/37035 are not being applied with this extension, for example this rule (currently on line 1440 of the style):

```css
.site-header-nav a { color: #e2e2e2 !important; }
```

When I manually move the rule to the beginning of the style, it is applied correctly. Same rules work in Stylish for Chrome and Firefox (These are the topic tags on Github repos like https://github.com/StylishThemes/GitHub-Dark).

I thought that another explanation could be that something might throwing off Safari's CSS parser,but I'm not seeing anything logged in the browser console at least.

**Comment by 350d** [comment]
@silverwind did you tried to disable css minification  in Stylish settings already?

**Comment by silverwind** [comment]
Yes, it's disabled and I reinstalled the style multiple times with that setting.

**Comment by 350d** [comment]
As i can see - complete style injected without any problems and complete style availabe to edit and update, so, should be a problem in style itself.

**Comment by silverwind** [comment]
Do you know if there is there a debug console in Safari that points out CSS errors in user styles?

**Comment by 350d** [comment]
I've added last line with debug rule here and everything works fine:

![screenshot 2017-02-16 14 48 25](https://cloud.githubusercontent.com/assets/429208/23038189/26aa46be-f457-11e6-8bec-5b51f3ea148c.png)

**Comment by 350d** [comment]
`.site-header-nav a` available two times in this style and if you trying to move last one to beginning of the style, you still have another rule in other place

**Comment by silverwind** [comment]
Sorry, meant to post this better example:

```css
.topic-tag { background: #182030 !important; }
```

**Comment by silverwind** [comment]
Still trying to find the cause, but I guess it's not an issue with the extension. Maybe a unquoted data-uri or something similar is throwing off Safari's parser.

**Comment by 350d** [comment]
Try latest version 1.9.8 and report back please.

**Comment by silverwind** [comment]
It works! I had to reinstall the style two times, but now everything is fine.

**Comment by 350d** [comment]
cool, i guess problem was in minification and way to check this option status, so, enjoy 😀 I will resubmit this version ASAP to Apple

**Comment by silverwind** [comment]
Nice. The issue was looking like a section in the middle of the style was "invisible" to Safari, really weird.

Which minfier (and options) are you using? I can recommend https://github.com/jakubpawlowicz/clean-css btw :)

**Comment by 350d** [comment]
YUI Compressor
