### ISSUE TITLE
Sorting the “Manage” screen’s list of styles?

### ISSUE THREAD

**Issue by handcoding** [350d/stylish#26]
I’m using Stylish 1.9.8 with Safari 10.0.3 (on macOS 10.11.6). And I was wondering if it might be possible to case-insensitively sort the userstyles on Stylish's “Manage” screen?

As far as I can tell, the “Manage” screen doesn’t appear to be sorted in a pattern that I can identify, which kinda makes it harder to find/edit an existing userstyle in the list. 

For instance, here’s an excerpt from my Stylish → Manage screen:
![stylish 1-9-8 - manage screen](https://cloud.githubusercontent.com/assets/118319/23762412/7c3230aa-04bb-11e7-9a73-756a706c5d52.png)

**Comment by 350d** [comment]
#

**Comment by handcoding** [comment]
Thanks a bunch, @350d! ☆
