### ISSUE TITLE
Userstyles not working on Feedly

### ISSUE THREAD

**Issue by jwill86** [350d/stylish#27]
I’m using Stylish 1.9.8 with Release 25 (Safari 10.2, WebKit 12604.1.8.1.2) (on macOS 10.12.3) Styles are only applied to Feedly when manually turning them on/off. This is the only site I have encounter this problem.

**Comment by 350d** [comment]
Can you provide style url here?

**Comment by 350d** [comment]
Try version 1.9.9 from website - http://sobolev.us/stylish/

**Comment by jwill86** [comment]
loaded with no problems in 1.9.9, thank you.

**Comment by jwill86** [comment]
Installed 1.9.9 styles only apply after refresh on feedly. This style for example https://userstyles.org/styles/120980/the-dark-and-flat-feedly

**Comment by 350d** [comment]
Works fine for me, except style errors and white background sometimes while scrolling
