### ISSUE TITLE
Styles not listed under toolbar button menu

### ISSUE THREAD

**Issue by Mr-Tao** [350d/stylish#30]
I have upgraded stylish from 1.x to 2.0.0 on Safari using extensions gallery. As a result none of my styles are listed and _No styles installed_ is displayed instead. Styles however are preserved and applied as before. I just cannot enable/disable them using the button menu.
It seems to be #17 hitting again.

**Comment by 350d** [comment]
Can you try to export your styles, reinstall the extension and import your styles again?

**Comment by Mr-Tao** [comment]
@350d Reinstallation of Stylish indeed fixed the issue.
I do not know whether this is relevant or not, but before reinstallation the extension resided in
`Library/Caches/com.apple.Safari/Extensions/Stylish-2.safariextension
Library/Safari/Extensions/Stylish-2.safariextz`
while now it is in
`Library/Caches/com.apple.Safari/Extensions/Stylish.safariextension
Library/Safari/Extensions/Stylish.safariextz`.
Also the message in menu was `No styles installed` while it is `🔴 No styles for this page…` now.
