### ISSUE TITLE
[Question] Theme persistence?

### ISSUE THREAD

**Issue by rockchalkwushock** [350d/stylish#31]
I just found about this through the Github Dark Theme I found here on Github and wanted to know is there a way to persist the theme so the page does not load first and then apply the theme? I love the darker theme; but loading white & then going to dark is probably hurting my :eyes: even more.

Browser: Safari 10.1.1

**Comment by 350d** [comment]
Stylish trying to inject styles as soon as it possible. On first step style injected to the `head`, `body` or `document` and on `domready` stylish trying to move your style to the end of the`body` to override all other styles. So, if you still have white flashes - the only way to fix it is to add some extra rules to the style itself, like disable all `transitions` for `html`, `body` and other affected elements etc.
