### ISSUE TITLE
Not Work At All

### ISSUE THREAD

**Issue by ColdOxygen** [350d/stylish#32]
There are two issues.
1. The extension always shows 'no styles for this page', even at google.com. I have to click 'find more' to install.
2. Even if I installed the styles, they didn't work at all.

**Comment by L3rchal** [comment]
Yeah happens sometimes .... just restart extension by uncheck a check again mark for stylish in settings to unable and able again. 
Works for me.

**Comment by 350d** [comment]
This issue still exist in v 2.0.3?
