### ISSUE TITLE
Remove MacKeeper Adverts on configuration page

### ISSUE THREAD

**Issue by Jahhein** [350d/stylish#38]
I implore you to remove the MacKeeper advertisement from the Stylish extension settings page. Mackeeper is basically a form of malware/spyware for anyone's Mac computer. Deceptive claims and bad practices from MacKeeper make this advertisement a security issue for with Stylish.

Please see: [MacKeeper Lawsuit page](https://mackeeper.com/settlement) for more details.

**Comment by 350d** [comment]
Promo page removed in v.2.0.7 and new version submitted to Apple already. Promo banner in extension settings still available and its up to you to use this app or not.
