### ISSUE TITLE
White text input fields

### ISSUE THREAD

**Issue by ondrejfuhrer** [350d/stylish#42]
Hello,

I'm experiencing a strange issue with the last few versions of the Stylish extension. On a pages, that I don't use any "theme", I started to get a "white" text inside text input fields. After deactivating the extension everything is back to normal. 

Example: https://www.edna.cz
With stylish extension: 
<img width="347" alt="screencapture at thu nov 23 09 13 55 cet 2017" src="https://user-images.githubusercontent.com/10830505/33163467-f2ad7d22-d02e-11e7-8038-c4f0352d1ee3.png">

Without stylish extension:
<img width="346" alt="screencapture at thu nov 23 09 14 22 cet 2017" src="https://user-images.githubusercontent.com/10830505/33163475-fb71f636-d02e-11e7-8169-a5794cfa86aa.png">

Can someone take a look, what is wrong?

**Comment by tzm41** [comment]
There is a bug that a non-applicable style gets applied to a website. I believe the author has uploaded a newer version of the extension which should fix the issue.

**Comment by ondrejfuhrer** [comment]
@tzm41 Thanks! So far I still have 2.0.5 extension version and there is 2.0.8 here in the repo, so hopefully, it gets updated soon 🙂

**Comment by ondrejfuhrer** [comment]
But I can confirm (I installed the extension from the repo), that in the 2.0.8 the problem does not occur anymore.
