### ISSUE TITLE
No option to create new styles on Safari. 

### ISSUE THREAD

**Issue by jtheletter** [350d/stylish#46]
For Stylish on macOS Chrome, I click the Stylish toolbar icon, then the vertical ellipsis, then "Create New Style". 

On Safari, clicking the Stylish toolbar button only reveals a list of installed styles, a button to "Find More", and a button to "Manage". "Manage" lets me edit, but I don't see an option to create new. 

Stylish Version 2.0.8

Safari Version 11.1 (13605.1.33.1.4)

**Comment by 350d** [comment]
Just select `edit` from Stylish menu and create new style.

**Comment by jtheletter** [comment]
How unexpected. Thank you.
